name: Acesso

on: 
  workflow_call:

    inputs:
      site:
        required: true
        type: string

    outputs:
      codigo_retorno:
        value: ${{ jobs.acesso.outputs.codigo_retorno }}

jobs:
  acesso:
    outputs:
      codigo_retorno: ${{ steps.curl.outputs.codigo_retorno }}
    runs-on: ubuntu-latest
    steps:

      - name: rodar o curl
        id: curl
        run: |
          curl -u ${{ vars.usuario }}:${{ secrets.teste }} ${{ inputs.site }}
          echo codigo_retorno=$? >> $GITHUB_OUTPUT
  teste:
    uses: backuplinux-sudo/reutilizaveis/.github/workflows/teste.yaml@main