name: Acesso

on: 
  workflow_call:

    inputs:
      site:
        required: true
        type: string
    secrets:
      usuario:
        required: true
      senha:
        required: true

jobs:
  acesso:
    runs-on: ubuntu-latest
    steps:

      - name: rodar o curl
        run: curl -u ${{ vars.usuario }}:${{ secrets.teste }} ${{ inputs.site }}