name: Acesso

on: 
  workflow_call:

    inputs:
      site:
        required: true
        type: string

    outputs:
      saida:
        value: ${{ jobs.acesso.outputs.saida }}

jobs:
  acesso:
    outputs:
      saida: ${{ steps.curl.outputs.saida }}
    runs-on: ubuntu-latest
    steps:

      - name: rodar o curl
        id: curl
        run: |
          curl -u ${{ vars.usuario }}:${{ secrets.teste }} ${{ inputs.site }}
          echo saida=$? >> $GITHUB_OUTPUT