name: Chamada action reusable

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          echo "Raíz"
          ls -la
          echo ".github"
          ls -la .github
          echo "actions"
          ls -la .github/actions/
          echo "instalacoes"
          ls -la .github/actions/instalacoes
      - uses: ./.github/actions/instalacoes/
        with:
          workflow: ${{ github.workflow }}

